### PR TITLE
(PDK-1684) Support long filenames

### PR DESCRIPTION
**Pull request by DavidS**

### CODE REVIEW

**Comment by DavidS** [comment]
as the testcase in the last commit here shows, minitar 0.9 is able to build tarballs that it can't correctly unpack. Dropping this for now.

**Comment by DavidS** [comment]
GNU tar was completley fine unpacking the tarball.

**Comment by carabasdaniel** [comment]
Related to: https://tickets.puppetlabs.com/browse/PUP-10924

**Comment by sanfrancrisko** [comment]
This should be completed - we should validate then close this issue

**Comment by michaeltlombardi** [comment]
Validated locally, `pdk build` worked on a module with files as long as 313 characters, which would have tripped this problem.

**Pull request closed without merging**
