### PR TITLE
(maint) Various base maintenance adjustments

### PR DESCRIPTION
**Pull request by DavidS**

### CODE REVIEW

**Comment by DavidS** [comment]
I didn't manage to get a remotely useful test pipeline up and running with ruby2.1 (see https://github.com/DavidS/puppet-modulebuilder/commit/4d43d1968102898a0ff240bfe342ea28a08ba0c6 for my last state before I gave up). So this only contains the lowering of the ruby lower bound.

**Comment by DavidS** [comment]
Without it dependabot doesn't work. is this a case of either/or?

**Comment by glennsarti** [comment]
Given that the only thing that this gem will depend on is minitar and pathspec is dependabot even needed?

**Comment by DavidS** [comment]
I gave this another go on my windows test VM. Adding the platform for windows didn't impact functionality on linux, even when installing gems with native binaries like `puppet`. so https://github.com/DavidS/puppet-modulebuilder/commit/eddc90e17fb7d2d20bed9ddec4b1c99a72af990d can go in with no bother.

When adding the rubocop changes (see https://github.com/DavidS/puppet-modulebuilder/commit/3e6ef8e243498ed28ec35a33f0588f604a67cd5f) it breaks with
* if rubocop is installed: "Error: RuboCop found unsupported Ruby version 2.1 in `TargetRubyVersion` parameter (in .rubocop.yml). 2.1-compatible analysis was dropped after version 0.58."
* if rubocop is not installed: "LoadError: cannot load such file -- rubocop/rake_task"

**Comment by scotje** [comment]
Agree with @glennsarti about not including `Gemfile.lock`, it is considered a bad practice to version control `Gemfile.lock` in a gem that is intended to be composed into other projects. The runtime and development dependencies should be listed in the `.gemspec` unless that's not possible for some reason.

https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/ (I know this is 10 years old at this point but I don't think the logic has fundamentally changed?)

**Comment by DavidS** [comment]
TIL: dependabot can update the gemspec: https://dependabot.com/ruby/; I'll get that fixed.

**Pull request merged**
