### PR TITLE
(maint) Add acceptance tests

### PR DESCRIPTION
**Pull request by glennsarti**
This PR adds two simple acceptance tests for the module builder.  The tests
build an example Puppet Module (motd) and then installs it via Puppet. The tests
ensure that the extacted content is as expected as the source.

### CODE REVIEW

**Comment by glennsarti** [comment]
Note the large file diff (+3,028) is due to the large test fixture, not that actual test suite.

**Comment by DavidS** [comment]
You could pull in the module from github during the test to save on the lines committed. Or create a new module to reduce ballast in spec/fixtures.

**Comment by glennsarti** [comment]
Yeah I thought about that... decided to just vendor it in to reduce dependencies.  Worst case I could just go through all the files and add single line comments instead of having "real" content"

**Comment by glennsarti** [comment]
Travis:

```
Puppet::Modulebuilder::Builder
  with a real module that is built
    builds the module and returns the path to the tarball
    which is installed via Puppet
      expands the expected paths
Finished in 1.18 seconds (files took 0.15477 seconds to load)
2 examples, 0 failures
```

Appveyor:
```
Puppet::Modulebuilder::Builder
  with a real module that is built
    builds the module and returns the path to the tarball
    which is installed via Puppet
      expands the expected paths
Finished in 2.93 seconds (files took 0.39675 seconds to load)
2 examples, 0 failures
Coverage report generated for RSpec to C:/projects/puppet-modulebuilder/coverage. 126 / 156 LOC (80.77%) covered.
```

Tests are running and are green!

**Review by DavidS — APPROVED** [review]

**Pull request merged**
